worker_processes auto;

events {
    worker_connections 2048;
    multi_accept on;
}

error_log  /var/log/nginx/error.log notice;
pid        /tmp/nginx.pid;

http {
    include       mime.types;
    default_type  application/octet-stream;
    
    # Hide Nginx version
    server_tokens off;

    # Basic network optimization
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    include /etc/nginx/conf.d/*.conf;
}
